default:
	gcc main.c selection_sort.c -o sort
selection_sort:
	gcc main.c selection_sort.c -o sort
bb_sort:
	gcc main_char_array.c bubble_sort.c -o sort
merge_sort:
	gcc main.c merge_sort.c -o sort
binary_search:
	gcc main_sorted_array.c binary_search.c -o binary_search

