ex1:
	gcc ex1_string_on_heap.c ex1_driver_code.c -o ex1.o
	./ex1.o
ex2:
	gcc ex2_array_summation.c ex2_driver_code.c -o ex2.o
	./ex2.o
ex3:
	gcc ex3_caesar_cipher.c  ex3_driver_code.c -o ex3.o
	./ex3.o
ex4:
	gcc ex4_driver_code.c  ex4_sort_str_arr.c -o ex4.o
	./ex4.o
default:
	echo "Please specify exercise that you want to execute. E.g. make -Makefile ex1"
clean:
	rm -rf *.o

